# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HmF1WP5-R9hXatkctTgkP1T9RNTVMuPf
"""

list=[[1,2,3],[4,5,6],[7,8,9]]
print(list)

tuple=(3,5,7,8)
print(tuple)
print(tuple[2])

import pandas as pd
data = pd.DataFrame({
"Name": ["Jerlin", "Priya", "josh", "David"],
"Marks": [85, 92, 78, 88],
"passed": ["true","true","true","true"]
})
print(data)

import pandas as pd
student= ({"Name":"Jerlin","Marks":85,"passed":"true"},
         {"Name":"Priya", "Marks":92, "passed":"true"},
         {"Name":"josh", "Marks":99,"passed":"true"},
         {"Name":"David","Marks":88,"passed":"true"})
student_data=pd.DataFrame(student)
print("-------------------------")
print(student_data)
print("-------------------------")

def calculate_cgpa(marks,credits):
  total=0
  total_credits=0
  for i in range(len(marks)):
    total+=marks[i]*credits[i]
    total_credits+=credits[i]
  cgpa=total/total_credits
  return cgpa
marks=[9,6,9,7,8,10]
credits=[1,3,1,2,3,3]
cgpa=calculate_cgpa(marks,credits)
print("CGPA:", cgpa)

def cgpa(a,b):
  result=a/b
  return result
a=int(input("Enter the marks:"))
b=int(input("Enter the credits:"))
print(cgpa(a,b))