# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WWbPWTb_0-uLeuu5DOcmixVZAJwTfHpS
"""

import pandas as pd
import numpy as np

df=pd.read_csv('/content/Simple RFM Customer Segmentation - K Means Practice.csv')
df

df.drop("customer_id",axis=1,inplace=True)
df

import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans

X = df[['monetary_purchase_amt','frequency_purchase']]
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

kmean = KMeans(n_clusters=3, random_state=42)
clusters = kmean.fit_predict(X_scaled)
df['Cluster'] = clusters

kmean

centroids=kmean.cluster_centers_

plt.figure(figsize=(8,6))
plt.scatter(X_scaled[:,0],X_scaled[:,1],c=clusters,cmap='rainbow',s=40)
plt.scatter(centroids[:,0],centroids[:,1],color='black',s=200)
plt.xlabel('Monetary Purchase Amount')
plt.ylabel('Frequency Purchase')
plt.title('K-Means Clustering')
plt.show()
clusters_summary = df.groupby('Cluster')[['monetary_purchase_amt','frequency_purchase']].mean()
print(clusters_summary)

