# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_I82BXChEup1aY4ZiocGPMm40lnL__nl
"""

import pandas as pd

df = pd.read_csv("/content/student_performance_dataset (1).csv")
df

df.isna().sum()

len(df)

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import seaborn as sns                       #visualisation
import matplotlib.pyplot as plt             #visualisation
# %matplotlib inline
sns.set(color_codes=True)

df.count()

mu = df['Final_Exam_Score'].mean()
mu

df['Gender'].value_counts()

mod = df['Gender'].mode()
mod

train_test_split(x,y,test_size=0.2)

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

le = LabelEncoder()
df['Gender_Encoded'] = le.fit_transform(df['Gender'])
le = LabelEncoder()
df['Pass_Fail_Encoded'] = le.fit_transform(df['Pass_Fail'])

le = LabelEncoder()
df['Parental_Education_Level_Encoded'] = le.fit_transform(df['Parental_Education_Level'])
le = LabelEncoder()
df['Internet_Access_at_Home_Encoded'] = le.fit_transform(df['Internet_Access_at_Home'])
le = LabelEncoder()
df['Extracurricular_Activities_Encoded'] = le.fit_transform(df['Extracurricular_Activities'])

x = df.drop(['Student_ID', 'Gender', 'Pass_Fail', 'Parental_Education_Level', 'Internet_Access_at_Home', 'Extracurricular_Activities', 'Pass_Fail_Encoded'], axis=1)
y = df['Pass_Fail']
df

duplicate_rows_df = df[df.duplicated()]
print("number of duplicate rows: ", duplicate_rows_df.shape)

df.count()



